#! /bin/sh

sxhkd &

picom -b
feh --bg-fill ~/Downloads/39628.jpg
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config active_border_color '#ff85b8'
bspc config focused_border_color '#ff85b8'
bspc config normal_border_color '#43454b'
bspc config window_gap          4
bspc config top_padding 0

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
